### ISSUE TITLE
 DeprecationWarning: executable_path has been deprecated, please pass in a Service object

### ISSUE THREAD

**Issue by DrinkingJoe** [Rerum-Crea/Twitch-Account-Toolbox#3]
```C:\Users\tomas\Downloads\Twitch-Account-Toolbox-main\Modules\TAC.py:38: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(executable_path='./dep/geckodriver.exe')
Traceback (most recent call last):
  File "C:\Users\tomas\Downloads\Twitch-Account-Toolbox-main\Modules\TAC.py", line 38, in <module>
    driver = webdriver.Firefox(executable_path='./dep/geckodriver.exe')
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line```

**Comment by Necrownyx** [comment]
The deprecation issue is not a problem make sure the version of the package you are using is the same as the one in the requirements file
